# Generated by Django 3.2.9 on 2021-11-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название темы')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='link_to_resume',
            field=models.CharField(default='resume', max_length=200, verbose_name='Ссылка на резюме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='link_to_resume',
            field=models.CharField(default='resume', max_length=200, verbose_name='Ссылка на резюме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='publication_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время публикации'),
        ),
        migrations.AddField(
            model_name='respondingfreelancers',
            name='responding_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отклика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.IntegerField(verbose_name='Время на выполнение заказа'),
        ),
    ]
