# Generated by Django 3.2.9 on 2021-11-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211118_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
