# Generated by Django 3.2.9 on 2021-11-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='company',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Интересующие направления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=100, verbose_name='Фамилия пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.topic', verbose_name='Интересующие направления'),
            preserve_default=False,
        ),
    ]
