# Generated by Django 3.2.9 on 2021-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211125_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='publication_date',
            field=models.DateField(auto_now=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='respondingfreelancers',
            name='responding_date',
            field=models.DateField(auto_now=True, verbose_name='Время отклика'),
        ),
    ]
