# Generated by Django 3.2.9 on 2021-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211129_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='respondingfreelancers',
            name='responding_date',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='completed_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во выполненных заказов'),
        ),
        migrations.AddField(
            model_name='respondingfreelancers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
