# Generated by Django 3.2.9 on 2021-12-02 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20211201_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondingfreelancers',
            name='completed_order',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Прикрепленная работа'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to=settings.AUTH_USER_MODEL, verbose_name='id аккаунта'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_info', to=settings.AUTH_USER_MODEL, verbose_name='id аккаунта'),
        ),
        migrations.AlterField(
            model_name='respondingfreelancers',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
