# Generated by Django 3.2.9 on 2021-12-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211202_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='personal_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='personal_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Лицевой счет'),
        ),
    ]
