# Generated by Django 3.2.9 on 2021-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211207_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.IntegerField(verbose_name='Время на выполнение заказа (кол-во дней)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='respondingfreelancers',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус отклика'),
        ),
    ]
