# Generated by Django 3.2.9 on 2021-12-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211208_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='link_to_resume',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на резюме'),
        ),
    ]
