# Generated by Django 3.2.9 on 2021-12-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211210_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondingfreelancers',
            name='adoption_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата принятия отклика'),
        ),
        migrations.AlterField(
            model_name='respondingfreelancers',
            name='responding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата отклика'),
        ),
    ]
