# Generated by Django 3.2.9 on 2021-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211211_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='personal_account',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=9, verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='topics',
            field=models.ManyToManyField(blank=True, to='main.Topic', verbose_name='Интересующие направления'),
        ),
    ]
