# Generated by Django 3.2.9 on 2021-12-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211215_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='email', max_length=200, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='email',
            field=models.CharField(default='email', max_length=200, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
